//! Static enumeration of every event-handler kind reachable in the
//! gen2stadium2 flattened dex (measured: 76 names — vs ~330 in full gen9 PS).
//!
//! PS dispatches these by string composition (`'on' + event`); we dispatch by
//! enum + match. `dex_load` conformance tests assert that every callback name
//! occurring in `data/gen2stadium2.json` maps onto a variant here, so the
//! enum can never silently drift from the data.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Handler {
    // *Callback-style hooks (not `on*` but part of the same surface)
    BasePowerCallback,
    BeforeMoveCallback,
    BeforeTurnCallback,
    DamageCallback,
    DurationCallback,
    // on* hooks
    AfterHit,
    AfterMove,
    AfterMoveSecondary,
    AfterMoveSecondarySelf,
    AfterMoveSelf,
    AfterSubDamage,
    AfterSwitchInSelf,
    BasePower,
    BattleStart,
    BeforeMove,
    BeforeSwitchIn,
    BeforeSwitchOut,
    BeforeTurn,
    Damage,
    DisableMove,
    DragOut,
    Eat,
    Effectiveness,
    End,
    EntryHazard,
    Faint,
    FieldEnd,
    FieldResidual,
    FieldStart,
    FoeAfterMoveSelf,
    FoeBeforeSwitchOut,
    FoeSwitchOut,
    FoeModifySpD,
    Hit,
    HitField,
    Immunity,
    Invulnerability,
    LockMove,
    ModifyAccuracy,
    ModifyBoost,
    ModifyCritRatio,
    ModifyDamage,
    ModifyDef,
    ModifyMove,
    ModifySpA,
    ModifyType,
    MoveAborted,
    MoveFail,
    NegateImmunity,
    OverrideAction,
    PrepareHit,
    Residual,
    Restart,
    SetStatus,
    SideEnd,
    SideStart,
    SourceAccuracy,
    SourceBasePower,
    SourceInvulnerability,
    SourceModifyDamage,
    StallMove,
    Start,
    SwitchIn,
    TakeItem,
    TrapPokemon,
    Try,
    TryAddVolatile,
    TryBoost,
    TryEatItem,
    TryHit,
    TryImmunity,
    TryMove,
    TryPrimaryHit,
    Type,
    Update,
    UseMoveMessage,
    Weather,
    WeatherModifyDamage,
}

impl Handler {
    /// Maps a PS callback name (`"onTryHit"`, `"basePowerCallback"`,
    /// `"condition.onStart"` → last segment) onto a variant.
    pub fn from_name(name: &str) -> Option<Handler> {
        let name = name.rsplit('.').next().unwrap_or(name);
        use Handler::*;
        Some(match name {
            "basePowerCallback" => BasePowerCallback,
            "beforeMoveCallback" => BeforeMoveCallback,
            "beforeTurnCallback" => BeforeTurnCallback,
            "damageCallback" => DamageCallback,
            "durationCallback" => DurationCallback,
            "onAfterHit" => AfterHit,
            "onAfterMove" => AfterMove,
            "onAfterMoveSecondary" => AfterMoveSecondary,
            "onAfterMoveSecondarySelf" => AfterMoveSecondarySelf,
            "onAfterMoveSelf" => AfterMoveSelf,
            "onAfterSubDamage" => AfterSubDamage,
            "onAfterSwitchInSelf" => AfterSwitchInSelf,
            "onBasePower" => BasePower,
            "onBattleStart" => BattleStart,
            "onBeforeMove" => BeforeMove,
            "onBeforeSwitchIn" => BeforeSwitchIn,
            "onBeforeSwitchOut" => BeforeSwitchOut,
            "onBeforeTurn" => BeforeTurn,
            "onDamage" => Damage,
            "onDisableMove" => DisableMove,
            "onDragOut" => DragOut,
            "onEat" => Eat,
            "onEffectiveness" => Effectiveness,
            "onEnd" => End,
            "onEntryHazard" => EntryHazard,
            "onFaint" => Faint,
            "onFieldEnd" => FieldEnd,
            "onFieldResidual" => FieldResidual,
            "onFieldStart" => FieldStart,
            "onFoeAfterMoveSelf" => FoeAfterMoveSelf,
            "onFoeBeforeSwitchOut" => FoeBeforeSwitchOut,
            "onFoeSwitchOut" => FoeSwitchOut,
            "onFoeModifySpD" => FoeModifySpD,
            "onHit" => Hit,
            "onHitField" => HitField,
            "onImmunity" => Immunity,
            "onInvulnerability" => Invulnerability,
            "onLockMove" => LockMove,
            "onModifyAccuracy" => ModifyAccuracy,
            "onModifyBoost" => ModifyBoost,
            "onModifyCritRatio" => ModifyCritRatio,
            "onModifyDamage" => ModifyDamage,
            "onModifyDef" => ModifyDef,
            "onModifyMove" => ModifyMove,
            "onModifySpA" => ModifySpA,
            "onModifyType" => ModifyType,
            "onMoveAborted" => MoveAborted,
            "onMoveFail" => MoveFail,
            "onNegateImmunity" => NegateImmunity,
            "onOverrideAction" => OverrideAction,
            "onPrepareHit" => PrepareHit,
            "onResidual" => Residual,
            "onRestart" => Restart,
            "onSetStatus" => SetStatus,
            "onSideEnd" => SideEnd,
            "onSideStart" => SideStart,
            "onSourceAccuracy" => SourceAccuracy,
            "onSourceBasePower" => SourceBasePower,
            "onSourceInvulnerability" => SourceInvulnerability,
            "onSourceModifyDamage" => SourceModifyDamage,
            "onStallMove" => StallMove,
            "onStart" => Start,
            "onSwitchIn" => SwitchIn,
            "onTakeItem" => TakeItem,
            "onTrapPokemon" => TrapPokemon,
            "onTry" => Try,
            "onTryAddVolatile" => TryAddVolatile,
            "onTryBoost" => TryBoost,
            "onTryEatItem" => TryEatItem,
            "onTryHit" => TryHit,
            "onTryImmunity" => TryImmunity,
            "onTryMove" => TryMove,
            "onTryPrimaryHit" => TryPrimaryHit,
            "onType" => Type,
            "onUpdate" => Update,
            "onUseMoveMessage" => UseMoveMessage,
            "onWeather" => Weather,
            "onWeatherModifyDamage" => WeatherModifyDamage,
            _ => return None,
        })
    }
}
