//! nc2000-engine: Rust port of Pokemon Showdown's `[Gen 2] NC 2000`
//! (mod gen2stadium2) battle engine, scoped to exactly that format.
//!
//! Reference implementation: the PS repo (see README for the pinned commit in
//! `data/gen2stadium2.json` meta). Conformance is defined as bit-exact
//! snapshot parity against fixtures generated by `tools/gen-fixtures.js`.

pub mod battle;
pub mod choice;
pub mod dex;
pub mod events;
pub mod prng;
pub mod state;
