import { locale } from "./i18n";

const strings = {
  unexpectedError: { ja: "処理を完了できませんでした: {0}", en: "Could not complete the operation: {0}" },
  relaxedLevels: { ja: "このパーティは、選ぶ3匹のレベル合計が155を超えていても対戦できます。", en: "This team can battle even when the three selected Pokémon exceed the level total of 155." },
  warning: { ja: "警告: {0}", en: "Warning: {0}" },
  legalTeam: { ja: "大会ルールに合っています。", en: "This team follows the tournament rules." },
  opponents: { ja: "対戦相手", en: "Opponents" },
  games: { ja: "試合", en: "Games" },
  wins: { ja: "勝", en: "Wins" },
  losses: { ja: "負", en: "Losses" },
  ties: { ja: "引分", en: "Ties" },
  caps: { ja: "打切", en: "Capped" },
  winRate: { ja: "勝率", en: "Win rate" },
  score: { ja: "引き分けを含む成績", en: "Score including ties" },
  interval: { ja: "推定の幅", en: "Estimated range" },
  overall: { ja: "総合", en: "Overall" },
  productBudget: { ja: "{0}回(実際のボットと同じ)", en: "{0} (live bot)" },
  quickBudget: { ja: "{0}回(簡易計測)", en: "{0} (quick estimate)" },
  evaluateTitle: { ja: "NC2000 — パーティ強度測定", en: "NC2000 — Team evaluation" },
  defaultOpponent: { ja: "基本の相手{0}", en: "Default opponent {0}" },
  evaluationStopped: { ja: "停止しました。終わっていない2戦は、再開したときにやり直します。", en: "Stopped. The unfinished pair of games will be replayed when you resume." },
  preparingBattle: { ja: "対戦を準備しています…", en: "Preparing battles…" },
  battleStartError: { ja: "対戦を開始できません: {0}", en: "Could not start the battle: {0}" },
  evaluationError: { ja: "エラーで停止しました。終わった対戦の結果は残っています。", en: "Stopped due to an error. Completed results have been kept." },
  selectingPokemon: { ja: "ポケモンを選んでいます", en: "Selecting Pokémon" },
  thinkingTurn: { ja: "{0}ターン目・次の手を考えています", en: "Turn {0}: choosing the next action" },
  evaluationProgress: { ja: "対戦 {0} / {1} · {2}", en: "Game {0} / {1} · {2}" },
  aggregationStopped: { ja: "結果の集計中に停止しました。", en: "Stopped while collecting results." },
  evaluationDone: { ja: "指定した試合数の計測が完了しました。", en: "All requested games have finished." },
  evaluationStartError: { ja: "計測を開始できませんでした。", en: "Could not start the evaluation." },
  evaluateEyebrow: { ja: "NC2000 パーティ診断", en: "NC2000 Team evaluation" },
  evaluateHeading: { ja: "パーティの強さを調べる", en: "Evaluate your team's strength" },
  evaluateIntro: { ja: "ポケモンを登録すると、コンピューター同士で対戦して勝率を調べます。相手の技や持ち物は、対戦で判明するまで見えないルールです。", en: "Enter a team to measure its win rate in automated battles. The opponent's moves and items remain hidden until revealed in battle." },
  loadingBattleData: { ja: "対戦データを読み込んでいます…", en: "Loading battle data…" },
  tabRuns: { ja: "このタブの計測", en: "Evaluations in this tab" },
  runSummary: { ja: "{0} UTC · {1}戦 · {2}", en: "{0} UTC · {1} games · {2}" },
  yourTeam: { ja: "自分のパーティ", en: "Your team" },
  teamHelp: { ja: "ポケモンを選び、レベル・持ち物・技を入力してください。6匹まで登録できます。", en: "Choose up to six Pokémon and enter their levels, items, and moves." },
  importText: { ja: "テキストから読み込む", en: "Import from text" },
  importTextHelp: { ja: "他のツールからコピーしたパーティ情報を貼り付けられます。", en: "Paste a team copied from another tool." },
  importTeam: { ja: "パーティを読み込む", en: "Import a team" },
  teamFile: { ja: "パーティファイル", en: "Team file" },
  ruleWarningHelp: { ja: "大会ルール違反は警告を表示し、対戦に参加できます。", en: "Teams that break tournament rules can still battle, with warnings." },
  opponentSettings: { ja: "対戦相手の設定", en: "Opponent settings" },
  opponentHelp: { ja: "この中から、表示した確率で対戦相手を選びます。", en: "Each opponent is selected with the probability shown." },
  showSets: { ja: "技・持ち物を見る", en: "Show moves and items" },
  noItem: { ja: "持ち物なし", en: "No item" },
  noMoves: { ja: "技なし", en: "No moves" },
  opponentImportHelp: { ja: "今の設定をファイルに保存し、書き換えてから読み込むと相手を変更できます。", en: "To change opponents, save the settings to a file, edit it, and import it again." },
  saveOpponents: { ja: "相手の設定をファイルに保存", en: "Save opponent settings" },
  importOpponents: { ja: "相手の設定を読み込む（JSON）", en: "Import opponent settings (JSON)" },
  opponentFile: { ja: "相手の設定ファイル", en: "Opponent settings file" },
  evaluationSettings: { ja: "計測設定", en: "Evaluation settings" },
  gameCount: { ja: "試合数", en: "Number of games" },
  iterations: { ja: "考える回数", en: "Search iterations" },
  evenGames: { ja: "試合数は2以上の偶数にしてください。", en: "Enter an even number of games, at least 2." },
  testBudget: { ja: "テストビルド：実際に考える回数は{0}回です。", en: "Test build: the actual search budget is {0} iterations." },
  budgetHelp: { ja: "1手を決めるまでに試す回数です。実際のボットは {0} 回で、それより少ない回数は結果を早く見るための簡易計測です。両方に同じ回数を使い、先後を入れ替えて2戦ずつ対戦します。", en: "The number of search iterations used to choose each action. The live bot uses {0}; smaller budgets give a quicker estimate. Both sides use the same budget and play pairs of games with sides swapped." },
  evaluationResults: { ja: "計測と結果", en: "Evaluation and results" },
  newEvaluation: { ja: "別の計測を開始", en: "Start a new evaluation" },
  startEvaluation: { ja: "計測を開始", en: "Start evaluation" },
  resume: { ja: "再開", en: "Resume" },
  extendEvaluation: { ja: "追加計測", en: "Run more games" },
  stop: { ja: "停止", en: "Stop" },
  configurationChanged: { ja: "パーティ・対戦設定・アプリのバージョンが計測開始時と異なります。この結果に追加せず、新しい計測を始めてください。", en: "The team, battle settings, or app version has changed since this evaluation started. Start a new evaluation instead of adding to these results." },
  completedGames: { ja: "{0} / {1}戦完了 · {2}", en: "{0} / {1} games complete · {2}" },
  completedGamesLabel: { ja: "完了した試合", en: "Completed games" },
  saveResults: { ja: "結果をファイルに保存", en: "Save results to a file" },
  saveCsv: { ja: "表計算ソフト用に保存", en: "Save for a spreadsheet" },
  resultConditions: { ja: "この結果の条件と警告", en: "Conditions and warnings for these results" },
  startedAt: { ja: "開始: {0} UTC", en: "Started: {0} UTC" },
  emptyResults: { ja: "パーティを入力して計測を開始すると、総合成績と相手別成績がここに表示されます。", en: "Enter a team and start an evaluation to see overall and per-opponent results here." },
  statisticsHelp: { ja: "勝率は勝った試合の割合です。「引き分けを含む成績」では、引き分けと500ターンでの打ち切りを半勝として数えます。「推定の幅」は偶然によるばらつきの目安です。試合が少ない間は、結果も大きく変わります。", en: "Win rate is the fraction of games won. Score including ties counts ties and games capped at 500 turns as half a win. The estimated range indicates sampling uncertainty. Results can vary widely with only a few games." },
  resultsHelp: { ja: "このコンピューターが、指定した相手と対戦したときの成績です。結果は自動保存されません。再読み込みやタブを閉じる操作でリセットされます。残したい結果はファイルに保存してください。", en: "These results describe this bot playing against the specified opponents. Results are not saved automatically and are cleared when you reload or close the tab. Save them to a file to keep them." },
  suggestionsFor: { ja: "{0}の候補", en: "Suggestions for {0}" },
  noSuggestions: { ja: "候補がありません。名前を確かめてください。", en: "No matches. Check the name and try again." },
  none: { ja: "なし", en: "None" },
  editorInvalid: { ja: "読み込んだ内容を確認できません。「テキストから読み込む」で内容を直してください。", en: "Could not read this team. Use Import from text to correct it." },
  memberKey: { ja: "{0}{1}匹目", en: "{0}, Pokémon {1}" },
  teamMembers: { ja: "{0}のメンバー", en: "{0} members" },
  emptyMember: { ja: "未入力", en: "Not entered" },
  addPokemon: { ja: "＋ ポケモンを追加", en: "＋ Add Pokémon" },
  memberSpecies: { ja: "{0}のポケモン", en: "{0} species" },
  pokemon: { ja: "ポケモン", en: "Pokémon" },
  speciesExample: { ja: "例：カビゴン", en: "e.g. Snorlax" },
  level: { ja: "レベル", en: "Level" },
  memberLevel: { ja: "{0}のレベル", en: "{0} level" },
  memberItem: { ja: "{0}の持ち物", en: "{0} item" },
  item: { ja: "持ち物", en: "Item" },
  itemPlaceholder: { ja: "なし／名前で検索", en: "None / search by name" },
  memberMove: { ja: "{0}の技{1}", en: "{0} move {1}" },
  moveSlot: { ja: "技{0}", en: "Move {0}" },
  movePlaceholder: { ja: "技の名前で検索", en: "Search moves by name" },
  advancedStats: { ja: "個体値・育成状態など", en: "DVs, training, and more" },
  advancedStatsHelp: { ja: "指定しない場合は、個体値・育成状態・なつき度を最大として計算します。めざめるパワーの種類を指定した場合は、個体値を自動で合わせます。", en: "DVs, stat experience, and happiness default to their maximum values. Choosing a Hidden Power type automatically adjusts the DVs." },
  attack: { ja: "こうげき", en: "Attack" },
  defense: { ja: "ぼうぎょ", en: "Defense" },
  speed: { ja: "すばやさ", en: "Speed" },
  special: { ja: "とくしゅ", en: "Special" },
  dvSuffix: { ja: "の個体値", en: " DV" },
  memberDv: { ja: "{0}の{1}の個体値", en: "{0} {1} DV" },
  happiness: { ja: "なつき度", en: "Happiness" },
  memberHappiness: { ja: "{0}のなつき度", en: "{0} happiness" },
  training: { ja: "育成状態", en: "Stat experience" },
  memberTraining: { ja: "{0}の育成状態", en: "{0} stat experience" },
  trainingMax: { ja: "十分に育成（最大）", en: "Fully trained (maximum)" },
  trainingNone: { ja: "育成前（0）", en: "Untrained (0)" },
  trainingCustom: { ja: "読み込んだ個別の設定", en: "Imported individual values" },
  removePokemon: { ja: "このポケモンを外す", en: "Remove this Pokémon" },
  enterTeam: { ja: "パーティを入力してください。", en: "Enter a team." },
  teamSize: { ja: "ポケモンは1〜6匹で登録してください。", en: "Enter between 1 and 6 Pokémon." },
  missingSpecies: { ja: "{0}匹目: 種族を指定してください。", en: "Pokémon {0}: specify a species." },
  invalidLevel: { ja: "{0}匹目: レベルは1〜100の整数にしてください。", en: "Pokémon {0}: level must be an integer from 1 to 100." },
  invalidMoves: { ja: "{0}匹目: 技は4個以下で登録してください。", en: "Pokémon {0}: enter up to 4 moves." },
  invalidTeam: { ja: "パーティを構成できません。", en: "Could not build this team." },
  uniqueOpponentNames: { ja: "相手の名前は空欄にせず、重複しないようにしてください。", en: "Opponent names must be nonempty and unique." },
  missingWeight: { ja: "{0}: 出やすさを入力してください。", en: "{0}: enter a selection weight." },
  invalidDistribution: { ja: "相手の設定ファイルを確認してください。パーティと出やすさをまとめたJSONファイルが必要です。", en: "Check the opponent settings file. It must be a JSON file containing teams and selection weights." },
  incompleteOpponent: { ja: "相手の名前・出やすさ・パーティの情報が足りません。", en: "An opponent's name, selection weight, or team is missing." },
  noOpponents: { ja: "対戦相手を1件以上指定してください。", en: "Specify at least one opponent." },
  invalidWeight: { ja: "出やすさは0以上の数値にしてください。", en: "Selection weights must be finite numbers of 0 or more." },
  zeroWeights: { ja: "少なくとも1つの相手の出やすさを、0より大きくしてください。", en: "At least one opponent must have a selection weight greater than 0." },
  resultOrderError: { ja: "対戦結果の順序を確認できないため、計測を停止しました。", en: "The result order could not be verified. Evaluation stopped." },
  missingRequests: { ja: "終局前に両側の選択要求が消えました。", en: "Both sides lost their action requests before the battle ended." },
  noLegalAction: { ja: "P{0}: 選択できる手がありません。", en: "P{0}: no legal action is available." },
  switchTo: { ja: "{0}に交代", en: "Switch to {0}" },
  pass: { ja: "待機", en: "Pass" },
  selectPokemon: { ja: "ポケモンを選出", en: "Select Pokémon" },
  replayVersionError: { ja: "この棋譜は異なる版のエンジンで作られています。対応する版のページで開いてください。", en: "This replay was created with a different engine version. Open it with the matching version of the page." },
  missingReplay: { ja: "この記録には、再開用の棋譜が見つかりませんでした。対戦画面の「棋譜をコピー」でコピーした内容を貼り付けてください。", en: "No resumable replay was found. Paste the content copied using Copy replay on the battle screen." },
  invalidReplay: { ja: "棋譜を最後まで読み取れませんでした。コピーした内容が途中で切れていないか確認してください。", en: "Could not read the complete replay. Check that the copied text has not been cut off." },
  kifuTitle: { ja: "NC2000 — 別の手を試す", en: "NC2000 — Try another move" },
  battleDataError: { ja: "対戦データを読み込めませんでした。ページを読み込み直してください。", en: "Could not load battle data. Reload the page and try again." },
  noReplayScenes: { ja: "まだ試し直せる場面がありません。対戦を進めてから棋譜をコピーしてください。", en: "There are no positions to replay yet. Continue the battle, then copy its replay." },
  pasteReplayError: { ja: "対戦記録を貼り付けてください。", en: "Paste a battle record." },
  resumeSceneError: { ja: "この場面からの再開を準備できませんでした。棋譜は保持されています。別の場面を選んで試せます。", en: "Could not prepare this position. Your replay is still available; try another position." },
  chooseSceneAgain: { ja: "場面と手を選び直す", en: "Choose a position and move again" },
  originalMove: { ja: "元の手", en: "Original move" },
  backToScene: { ja: "← 場面と手を選び直す", en: "← Choose a position and move again" },
  compareMoves: { ja: "元の手と別の手を比べる", en: "Compare the original move with another move" },
  turnWithLabel: { ja: "{0}ターン目 · {1}", en: "Turn {0} · {1}" },
  kifuEyebrow: { ja: "NC2000 · 対戦の振り返り", en: "NC2000 · Battle review" },
  tryAnotherMove: { ja: "別の手を試す", en: "Try another move" },
  kifuIntro: { ja: "対戦記録から場面を選んで、続きを試せます。", en: "Choose a position from a battle record and try playing from there." },
  pasteReplay: { ja: "対戦記録を貼り付ける", en: "Paste a battle record" },
  pasteReplayHelp: { ja: "コピーした記録をそのまま貼り付けてください。棋譜コードやリンクでも読み込めます。", en: "Paste the copied record as it is. Replay codes and links also work." },
  pasteReplayPlaceholder: { ja: "ここに対戦記録を貼り付け", en: "Paste a battle record here" },
  loadingReplay: { ja: "記録を読み込んでいます…", en: "Loading record…" },
  loadReplay: { ja: "記録を読み込む", en: "Load record" },
  preparingData: { ja: "対戦データを準備しています…", en: "Preparing battle data…" },
  playBot: { ja: "botと対戦する", en: "Play against the bot" },
  loadAnotherReplay: { ja: "← 別の記録を読み込む", en: "← Load another record" },
  recordEnded: { ja: "で終了", en: " (finished)" },
  recordPartial: { ja: "まで記録", en: " (recorded so far)" },
  recordSummary: { ja: "あなた 対 bot · {0}ターン{1}", en: "You vs bot · {0} turns{1}" },
  choosePosition: { ja: "どこから試しますか？", en: "Where would you like to start?" },
  chooseScene: { ja: "1. 場面を選ぶ", en: "1. Choose a position" },
  resumePosition: { ja: "再開する場面", en: "Position to resume" },
  sceneOption: { ja: "{0}ターン目 · {1}が{2}", en: "Turn {0} · {1}: {2}" },
  previousScene: { ja: "前の場面", en: "Previous position" },
  nextScene: { ja: "次の場面", en: "Next position" },
  beforeTurn: { ja: "{0}ターン目・手を選ぶ前", en: "Turn {0}, before choosing actions" },
  you: { ja: "あなた", en: "You" },
  awaitingSwitch: { ja: "交代待ち", en: "Awaiting replacement" },
  originalChoicePrefix: { ja: "記録では、botが", en: "In the record, the bot chose " },
  originalChoiceSuffix: { ja: "を選びました。", en: "." },
  showJournal: { ja: "直前までの記録を見る", en: "Show the preceding battle log" },
  chooseBotMove: { ja: "2. botに選ばせる手", en: "2. Choose the bot's move" },
  useMove: { ja: "技を使う", en: "Use a move" },
  switchPokemon: { ja: "交代する", en: "Switch Pokémon" },
  chooseMethod: { ja: "3. 続きをどう試しますか？", en: "3. How would you like to continue?" },
  playYourself: { ja: "自分で対戦する", en: "Play yourself" },
  playYourselfHelp: { ja: "あなたは元のチームを操作します。", en: "You control your original team." },
  compareBots: { ja: "bot同士で比べる", en: "Compare with bots" },
  compareBotsHelp: { ja: "元の手と選んだ手で、続きを繰り返し対戦します。", en: "Replay the continuation repeatedly with the original and selected moves." },
  sameMoveWarning: { ja: "元の手と同じです。比較する別の手を選んでください。", en: "This is the original move. Choose a different move to compare." },
  continuationSummary: { ja: "{0}ターン目、botが「{1}」を選んだところから。", en: "Start at turn {0}, with the bot choosing “{1}”." },
  chooseMoveHelp: { ja: "試したい手を上から一つ選んでください。", en: "Choose a move to try from the options above." },
  preparingPosition: { ja: "局面を準備しています…", en: "Preparing position…" },
  playThisMove: { ja: "この手で対戦を始める", en: "Start a battle with this move" },
  compareTwoMoves: { ja: "この2つの手を比べる", en: "Compare these two moves" },
  exportReplayError: { ja: "この対戦の棋譜を準備できませんでした。", en: "Could not prepare a replay of this battle." },
  replayCopied: { ja: "棋譜をコピーしました。", en: "Replay copied." },
  copyReplayFallback: { ja: "下の欄から棋譜をコピーできます。", en: "You can copy the replay from the field below." },
  saveBattle: { ja: "この対戦を残す・試し直す", en: "Save or retry this battle" },
  saveBattleHelp: { ja: "棋譜を残しておくと、あとで好きな場面から別の手を試せます。", en: "Save the replay to try other moves from any position later." },
  copyReplay: { ja: "棋譜をコピー", en: "Copy replay" },
  newTab: { ja: "（新しいタブ）", en: " (new tab)" },
  replayToCopy: { ja: "コピーする棋譜", en: "Replay to copy" },
  manualCopyHelp: { ja: "欄を選ぶと全文が選択されます。端末の「コピー」を使ってください。", en: "Select the field to highlight all its text, then use your device's Copy command." },
  switchLabel: { ja: "交代: {0}", en: "Switch: {0}" },
  forkTitle: { ja: "NC2000 — 反実仮想フォーク対局", en: "NC2000 — Counterfactual battles" },
  forkLoadError: { ja: "フォーク定義を読み込めません: {0}", en: "Could not load the fork definition: {0}" },
  loading: { ja: "読み込み中…", en: "Loading…" },
  deleteForkConfirm: { ja: "このフォークの記録をすべて消去しますか？", en: "Delete all records for this fork?" },
  forkEyebrow: { ja: "反実仮想フォーク対局", en: "Counterfactual battles" },
  forkHeading: { ja: "記録された局面から、bot と繰り返し対戦する", en: "Replay a recorded position against the bot" },
  forkIntro: { ja: "対戦記録の1局面から対局を再開し、bot の初手の候補ごとに勝率を比べます。比べ方は2つあります。あなたが元の対戦と同じ側を持って bot と対戦するか、bot 同士で対戦させるかです。どちらも 2手目以降は bot がラダーと同じ仕組みで考えます。", en: "Resume a recorded position and compare win rates for the bot's possible first actions. You can play your original side against the bot, or let bots play both sides. From the second action onward, the bot uses the same search as on the ladder." },
  forkHelp: { ja: "あなたとの対戦では、bot の初手は候補手のどれか1つに固定され、どれになるかは対局ごとに無作為に決まり、ターンが進むまで分かりません。途中でやめた対局は投了（bot の勝ち）として記録します。記録はこのブラウザにだけ保存されます。", en: "In human games, the bot's first action is randomly chosen from the candidates for each game and stays hidden until the turn unfolds. Leaving a game counts as a forfeit (a bot win). Records are saved only in this browser." },
  loadFork: { ja: "フォーク定義を読み込む", en: "Load a fork definition" },
  forkFormatMiddle: { ja: "で作った", en: " output in " },
  forkFormatSuffix: { ja: "の JSON を選ぶか、貼り付けてください。", en: " format can be uploaded or pasted below." },
  forkFile: { ja: "フォーク定義ファイル", en: "Fork definition file" },
  loadPastedFork: { ja: "貼り付けた定義を読み込む", en: "Load pasted definition" },
  fork: { ja: "フォーク", en: "Fork" },
  startingPosition: { ja: "開始局面", en: "Starting position" },
  turn: { ja: "ターン {0}", en: "Turn {0}" },
  playerSide: { ja: "p{0} 側（元の対戦と同じ）", en: "Side p{0} (same as the original battle)" },
  botInformation: { ja: "bot の情報", en: "Bot information" },
  blindBot: { ja: "あなたの構築を知らない（ラダーと同じ）", en: "Does not know your team (same as the ladder)" },
  openBot: { ja: "あなたの構築を知っている（オープンシート）", en: "Knows your team (open team sheets)" },
  botBudget: { ja: "対戦での bot の思考量", en: "Bot search budget" },
  perActionBudget: { ja: "1手あたり {0} 回", en: "{0} iterations per action" },
  firstActionCandidates: { ja: "bot の初手の候補", en: "Bot's first-action candidates" },
  startGame: { ja: "対局を始める", en: "Start a game" },
  nextGame: { ja: "次の対局", en: "Next game" },
  humanResults: { ja: "あなたとの対戦結果", en: "Results against you" },
  tieCount: { ja: " {0} 分", en: " {0} ties" },
  humanResultsSummary: { ja: "{0} 局終了 — あなたの {1} 勝 {2} 敗 {3}", en: "{0} games finished — you: {1} wins, {2} losses{3}" },
  hiddenResultsHelp: { ja: "候補ごとの結果は伏せてあります。対局中に意識しないよう、予定の局数を終えてから表示してください。", en: "Results by candidate are hidden to avoid influencing your play. Reveal them after completing your planned games." },
  revealResults: { ja: "候補ごとの結果を表示", en: "Reveal results by candidate" },
  botFirstAction: { ja: "bot の初手", en: "Bot's first action" },
  gameTotal: { ja: "局数", en: "Games" },
  botWins: { ja: "bot 勝", en: "Bot wins" },
  botLosses: { ja: "bot 負", en: "Bot losses" },
  draws: { ja: "分", en: "Ties" },
  botWinInterval: { ja: "bot 勝率 (95%)", en: "Bot win rate (95%)" },
  firstCandidate: { ja: "1番目", en: "First candidate" },
  differenceFrom: { ja: "{0} との差", en: "Difference from {0}" },
  forkStatisticsHelp: { ja: "区間は Wilson の95%区間、p は Fisher の正確検定（両側）です。途中でやめた対局（ {0} 局）は bot の勝ちに含みます。", en: "Intervals are Wilson 95% intervals; p uses Fisher's two-sided exact test. The {0} forfeited games count as bot wins." },
  exportJsonl: { ja: "結果を書き出す (JSONL)", en: "Export results (JSONL)" },
  deleteRecords: { ja: "記録を消去", en: "Delete records" },
  youWin: { ja: "あなたの勝ち", en: "You win" },
  botWin: { ja: "bot の勝ち", en: "Bot wins" },
  draw: { ja: "引き分け", en: "Tie" },
  forfeited: { ja: "（投了）", en: " (forfeit)" },
  turnSuffix: { ja: "・ターン {0}", en: " · Turn {0}" },
  resumedTurn: { ja: "ターン {0} から再開", en: "Resumed from turn {0}" },
  preparingScene: { ja: "局面を準備中…", en: "Preparing position…" },
  forkGameTitle: { ja: "フォーク #{0}・ターン {1}", en: "Fork #{0} · Turn {1}" },
  forfeitConfirm: { ja: "この対局を投了しますか？ bot の勝ちとして記録されます。", en: "Forfeit this game? It will count as a bot win." },
  forfeit: { ja: "投了", en: "Forfeit" },
  remaining: { ja: "残り{0}", en: "{0} left" },
  yourAction: { ja: "あなたの行動", en: "Your action" },
  revealedFirstMove: { ja: "この対局の bot の初手: {0} {1}", en: "Bot's first action in this game: {0}{1}" },
  backToResults: { ja: "結果一覧へ", en: "Back to results" },
  battleError: { ja: "対戦中にエラーが起きました: {0}", en: "A battle error occurred: {0}" },
  workerError: { ja: "Worker エラー: {0}", en: "Worker error: {0}" },
  botComparison: { ja: "bot同士で比較", en: "Bot comparison" },
  botTrials: { ja: "bot 同士で検証", en: "Bot trials" },
  arenaHelp: { ja: "同じ局面から bot 同士で対戦させ、bot の初手ごとの勝率を比べます。各試行ではすべての候補手を同じ乱数で打つので、候補手の差は初手とその後の展開だけから生まれます。相手も bot が打ちます。", en: "Let bots play from the same position and compare win rates for each first action. Every candidate in a trial uses the same random seeds, so differences come from the first action and its continuation. The opponent is also a bot." },
  trialCount: { ja: "試行数", en: "Number of trials" },
  actionBudget: { ja: "思考量（1手あたり）", en: "Search iterations per action" },
  ladderBudgetSuffix: { ja: "（ラダーと同じ）", en: " (same as the ladder)" },
  arenaBudget: { ja: "{0} 回{1}", en: "{0} iterations{1}" },
  opponent: { ja: "相手", en: "Opponent" },
  protocolBot: { ja: "ラダーと同じ bot（相手視点の情報）", en: "Ladder bot (opponent's information)" },
  omniscientBot: { ja: "全情報を見る探索（skuct）", en: "Full-information search (skuct)" },
  seed: { ja: "シード", en: "Seed" },
  parallelism: { ja: "並列数", en: "Parallel games" },
  moreTrials: { ja: "さらに {0} 試行", en: "{0} more trials" },
  startTrials: { ja: "検証を開始", en: "Start trials" },
  clearResults: { ja: "結果を消去", en: "Clear results" },
  estimatedRemaining: { ja: " · 残り目安 {0}", en: " · Estimated remaining: {0}" },
  trialsConfigChanged: { ja: "（設定を変えたので、次の開始で新しい検証になります）", en: " (Settings changed; starting again will create a new run.)" },
  trialProgress: { ja: "{0} / {1} 試行 · 経過 {2} {3} {4}", en: "{0} / {1} trials · Elapsed {2}{3}{4}" },
  winLossTie: { ja: "{0}勝 · {1}敗 · {2}引き分け", en: "{0} wins · {1} losses · {2} ties" },
  cappedGames: { ja: " · {0}対戦は打ち切り", en: " · {0} games capped" },
  arenaCompleted: { ja: "{0}対戦を完了{1}", en: "{0} games completed{1}" },
  cliEquivalent: { ja: "CLI で同じ試行:", en: "Equivalent CLI command: " },
  exportToKeep: { ja: "残すには書き出してください。", en: "Export them to keep them." },
  arenaResultsHelp: { ja: "結果はこのページを閉じると消えます。{0}", en: "Results are lost when you close this page. {0}" },
  trials: { ja: "試行", en: "Trials" },
  differenceInterval: { ja: "{0} との差 (95%)", en: "Difference from {0} (95%)" },
  replay: { ja: "棋譜", en: "Replay" },
} as const;

export type ToolTextKey = keyof typeof strings;
export function toolText(key: ToolTextKey, ...args: (string | number | boolean | null | undefined)[]): string {
  return strings[key][locale()].replace(/\{(\d+)\}/g, (_, i: string) => typeof args[Number(i)] === "boolean" || args[Number(i)] == null ? "" : String(args[Number(i)]));
}
